/* 메뉴컨텐츠_관리그룹 */
CREATE TABLE mc_cms_staff_group (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	CMS_MENU_SEQ NUMERIC(11) NOT NULL COMMENT '메뉴_시퀀스',
	GROUP_SEQ NUMERIC(11) NOT NULL COMMENT '그룹_시퀀스',
	GROUP_NM VARCHAR(32) COMMENT '그룹명',
	REG_DT DATETIME COMMENT '등록일',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(30) COMMENT '등록자',
	ORDER_SEQ NUMERIC(11) DEFAULT 1 COMMENT '순서'
) COMMENT = '메뉴컨텐츠_관리그룹';
CREATE UNIQUE INDEX PRIMARY1 ON mc_cms_staff_group (SEQ);
ALTER TABLE mc_cms_staff_group ADD CONSTRAINT PRIMARY_KEY1 PRIMARY KEY (SEQ);


/* 메뉴별_개인정보_필터설정 */
CREATE TABLE mc_cms_menu_filter (
	SITE_ID NUMERIC(11) NOT NULL COMMENT '사이트_ID',
	CMS_MENU_SEQ NUMERIC(11) NOT NULL COMMENT '메뉴시퀀스',
	FILTER_YN CHAR(1) DEFAULT 'N' COMMENT '필터_YN',
	JUMIN_YN CHAR(1) DEFAULT 'N' COMMENT '주민번호_YN',
	BUSINO_YN CHAR(1) DEFAULT 'N' COMMENT '사업자_YN',
	BUBINO_YN CHAR(1) DEFAULT 'N' COMMENT '법인_YN',
	EMAIL_YN CHAR(1) DEFAULT 'N' COMMENT '이메일_YN',
	TEL_YN CHAR(1) DEFAULT 'N' COMMENT '전화번호_YN',
	CELL_YN CHAR(1) DEFAULT 'N' COMMENT '휴대폰_YN',
	CARD_YN CHAR(1) DEFAULT 'N' COMMENT '카드_YN'
) COMMENT = '메뉴별_개인정보_필터설정';
CREATE UNIQUE INDEX PRIMARY2 ON mc_cms_menu_filter (SITE_ID ASC, CMS_MENU_SEQ ASC);
ALTER TABLE mc_cms_menu_filter ADD CONSTRAINT PRIMARY_KEY2 PRIMARY KEY (SITE_ID, CMS_MENU_SEQ);


/* 만족도조사 */
CREATE TABLE mc_satisfaction (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	CMS_MENU_SEQ NUMERIC(11) COMMENT '메뉴_시퀀스',
	SCORE NUMERIC(11) NOT NULL COMMENT '점수',
	IP VARCHAR(17) COMMENT '아이피',
	REG_DT DATETIME COMMENT '등록일',
	ETC VARCHAR(2000) COMMENT '기타'
) COMMENT = '만족도조사';
CREATE UNIQUE INDEX PRIMARY3 ON mc_satisfaction (SEQ);
ALTER TABLE mc_satisfaction ADD CONSTRAINT PRIMARY_KEY3 PRIMARY KEY (SEQ);


/* 메뉴정보 */
CREATE TABLE mc_cms_menu (
	CMS_MENU_SEQ NUMERIC(11) NOT NULL COMMENT '메뉴_시퀀스',
	PARENT_MENU_SEQ NUMERIC(11) COMMENT '부모키',
	TITLE VARCHAR(255) NOT NULL COMMENT '메뉴명',
	MENU_ORDER NUMERIC(11) DEFAULT 1 COMMENT '표시순서',
	USE_YN VARCHAR(1) DEFAULT 'Y' NOT NULL COMMENT '사용여부',
	BLANK_YN VARCHAR(1) DEFAULT 'N' COMMENT '새창여부',
	MENU_TYPE VARCHAR(1) COMMENT '메뉴타입',
	TARGET_URL VARCHAR(128) COMMENT '링크주소',
	PROGRAM_NM VARCHAR(255) COMMENT '프로그램명',
	BOARD_SEQ NUMERIC(11) COMMENT '게시판_번호',
	CONTS CLOB COMMENT '내용',
	SITE_ID NUMERIC(11) DEFAULT 1 COMMENT '사이트_ID',
	REG_NM VARCHAR(32) COMMENT '등록자',
	REG_DT DATETIME COMMENT '등록일',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	MOD_DT DATETIME COMMENT '수정일',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
	CHILD_TYPE NUMERIC(11) COMMENT '자식타입',
	HEAD_HTML CLOB COMMENT '하단표시내용',
	TEMPLATE_TYPE NUMERIC(11) DEFAULT 1 COMMENT '템플릿_타입',
	MENU_URL VARCHAR(100) COMMENT '메뉴_URL',
	CUD_GROUP_SEQ VARCHAR(150) COMMENT '수정_삭제_권한시퀀스',
	R_GROUP_SEQ VARCHAR(150) COMMENT '읽기권한_시퀀스',
	MANAGE_URL VARCHAR(128) COMMENT '관리페이지_주소',
	TOP_YN CHAR(1) DEFAULT 'Y' COMMENT '상단메뉴_노출여부',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	INNER_YN CHAR(1) DEFAULT 'N' COMMENT '관리메뉴_탭에서_관리사용여부',
	SUB_PATH VARCHAR(20) COMMENT '위성 사이트사용시 서브패스',
	CMOD_ID VARCHAR(32) COMMENT '콘텐츠 수정자_아이디',
	CMOD_NM VARCHAR(32) COMMENT '콘텐츠 수정자 명',
	CMOD_DT DATETIME COMMENT '콘텐츠 수정일',
	TEMP_CONTS CLOB COMMENT '임시저장_내용',
	CCL_TYPE CHAR(1) COMMENT '저작물타입',
	NURI_TYPE CHAR(1) COMMENT '공공누리타입',
	TAG_NAMES VARCHAR(200) COMMENT '태그이름',
	ADD_PARAM VARCHAR(255) COMMENT '추가파라미터',
	FOOTER_HTML CLOB COMMENT '홈페이지 하단내용',
	SATISFACTION_YN CHAR(1) COMMENT '페이지 만족도 사용여부',
	MANAGE_YN CHAR(1) COMMENT '담당자 안내 사용여부'
) COMMENT = '메뉴정보';
CREATE UNIQUE INDEX PRIMARY4 ON mc_cms_menu (CMS_MENU_SEQ);
CREATE INDEX IDX_CMS_MENU_SORTORDER ON mc_cms_menu (PARENT_MENU_SEQ, MENU_ORDER);
ALTER TABLE mc_cms_menu ADD CONSTRAINT PRIMARY_KEY4 PRIMARY KEY (CMS_MENU_SEQ);


/* 관리회원 */
CREATE TABLE mc_member (
	MEMBER_ID VARCHAR(30) NOT NULL COMMENT '회원_ID',
	MEMBER_PW VARCHAR(100) COMMENT '회원_패스워드',
	MEMBER_NM VARCHAR(30) COMMENT '회원명',
	EMAIL VARCHAR(100) COMMENT '이메일',
	TEL VARCHAR(15) COMMENT '전화번호',
	CELL VARCHAR(15) COMMENT '휴대폰번호',
	GROUP_SEQ NUMERIC(11) COMMENT '그룹_시퀀스',
	LAST_LOGIN DATETIME COMMENT '마지막_로그인시간',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(30) COMMENT '수정자',
	MOD_DT DATETIME COMMENT '수정일',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(30) COMMENT '삭제자',
	DEL_DT DATETIME COMMENT '삭제일',
	USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
	DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
	ORDER_SEQ NUMERIC(11) COMMENT '순서',
	RESPONSIBILITIES VARCHAR(500) COMMENT '담당업무',
	POSITIONS VARCHAR(100) COMMENT '직위',
	BLOCK_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '블록여부',
	LOGIN_FAIL_CNT NUMERIC(11) DEFAULT 0 NOT NULL COMMENT '로그인_시도횟수',
	LAST_PW_DT DATETIME COMMENT '마지막_패스워드변경일',
	DI VARCHAR(100) COMMENT 'DI',
	BIRTH VARCHAR(8) COMMENT '생년월일',
	EMAIL_YN CHAR(1) DEFAULT 'N' COMMENT '이메일발송_허용',
	SMS_YN CHAR(1) DEFAULT 'N' COMMENT 'SMS발송_허용',
	REG_DT DATETIME COMMENT '등록일',
	MOD_IP VARCHAR(16) COMMENT '수정자_IP',
	DORMANCY_YN CHAR(1) DEFAULT 'N' COMMENT '휴면계정_여부'
) COMMENT = '관리회원';
CREATE UNIQUE INDEX PRIMARY5 ON mc_member (MEMBER_ID);
ALTER TABLE mc_member ADD CONSTRAINT PRIMARY_KEY5 PRIMARY KEY (MEMBER_ID);


/* 공통코드목록_상세 */
CREATE TABLE mc_common_code (
	CODE_SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	CODE_GROUP_SEQ NUMERIC(11) NOT NULL COMMENT '공통코드_시퀀스',
	CODE VARCHAR(32) NOT NULL COMMENT '코드값',
	CODE_NM VARCHAR(64) NOT NULL COMMENT '코드명',
	VAL1 VARCHAR(200) COMMENT 'VAL1',
	VAL2 VARCHAR(200) COMMENT 'VAL2',
	ETC VARCHAR(200) COMMENT '기타',
	USE_YN CHAR(1) NOT NULL COMMENT '사용여부',
	ORDER_SEQ NUMERIC(11) DEFAULT 1 NOT NULL COMMENT '순서',
	REG_ID VARCHAR(20) COMMENT '등록자_ID',
	REG_NM VARCHAR(20) COMMENT '등록자',
	REG_IP VARCHAR(15) COMMENT '등록자_IP',
	REG_DT DATETIME COMMENT '등록일',
	MOD_ID VARCHAR(20) COMMENT '수정자_ID',
	MOD_NM VARCHAR(20) COMMENT '수정자',
	MOD_IP VARCHAR(15) COMMENT '수정자_IP',
	MOD_DT DATETIME COMMENT '수정일',
	DEL_ID VARCHAR(20) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(20) COMMENT '삭제자',
	DEL_IP VARCHAR(15) COMMENT '삭제자_IP',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) COMMENT = '공통코드목록_상세';
CREATE UNIQUE INDEX PRIMARY6 ON mc_common_code (CODE_SEQ, CODE_GROUP_SEQ ASC);
ALTER TABLE mc_common_code ADD CONSTRAINT PRIMARY_KEY6 PRIMARY KEY (CODE_SEQ, CODE_GROUP_SEQ);


/* 메뉴컨텐츠_관리회원 */
CREATE TABLE mc_cms_staff (
	CMS_STAFF_SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	CMS_MENU_SEQ NUMERIC(11) NOT NULL COMMENT '메뉴_시퀀스',
	GROUP_SEQ NUMERIC(11) NOT NULL COMMENT '그룹_시퀀스',
	GROUP_NM VARCHAR(32) COMMENT '그룹명',
	MEMBER_NM VARCHAR(30) COMMENT '회원명',
	MEMBER_ID VARCHAR(30) COMMENT '회원_ID',
	REG_DT DATETIME COMMENT '등록일',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(30) COMMENT '등록자',
	ORDER_SEQ NUMERIC(11) DEFAULT 1 COMMENT '순서'
) COMMENT = '메뉴컨텐츠_관리회원';
CREATE UNIQUE INDEX PRIMARY7 ON mc_cms_staff (CMS_STAFF_SEQ);
ALTER TABLE mc_cms_staff ADD CONSTRAINT PRIMARY_KEY7 PRIMARY KEY (CMS_STAFF_SEQ);

/* 팝업_목록 */
CREATE TABLE mc_popupzone (
	POPUPZONE_SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스 ',
	TITLE VARCHAR(128) COMMENT '제목 ',
	LINK_YN CHAR(1) COMMENT '링크_사용여부 ',
	LINK_URL VARCHAR(256) COMMENT '링크_URL ',
	LINK_TARGET VARCHAR(16) COMMENT '새창 ',
	FILE_PATH VARCHAR(128) COMMENT '파일경로 ',
	USE_YN CHAR(1) COMMENT '사용여부 ',
	ORDER_SEQ VARCHAR(5) DEFAULT '99999' COMMENT '순서 ',
	REG_DT DATETIME COMMENT '등록일 ',
	REG_ID VARCHAR(30) COMMENT '등록자_ID ',
	REG_NM VARCHAR(32) COMMENT '등록자 ',
	MOD_DT DATETIME COMMENT '수정일 ',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID ',
	MOD_NM VARCHAR(32) COMMENT '수정자 ',
	DEL_DT DATETIME COMMENT '삭제일 ',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID ',
	DEL_NM VARCHAR(32) COMMENT '삭제자 ',
	DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부 ',
	START_DT DATETIME COMMENT '게시_시작일 ',
	END_DT DATETIME COMMENT '게시_종료일 ',
	ALT VARCHAR(500) COMMENT '설명 ',
	X_COORD VARCHAR(20) COMMENT 'X좌표 ',
	Y_COORD VARCHAR(20) COMMENT 'Y좌표 ',
	SITE_ID VARCHAR(20) COMMENT '사이트_ID',
	SELECTER VARCHAR(20) COMMENT '구분 '
) COMMENT = '팝업_목록';
CREATE UNIQUE INDEX PRIMARY8 ON mc_popupzone (POPUPZONE_SEQ);
ALTER TABLE mc_popupzone ADD CONSTRAINT PRIMARY_KEY8 PRIMARY KEY (POPUPZONE_SEQ);

/* 게시판설정_커스텀_컬럼_타입 */
CREATE TABLE mc_board_column (
	ORDER_NUM NUMERIC(11) NOT NULL COMMENT '시퀀스',
	COL_CODE VARCHAR(20) COMMENT '컬럼_코드',
	COL_KOR VARCHAR(20) COMMENT '컬럼_제목',
	COL_HELPER VARCHAR(4000) COMMENT '컬럼_설명',
	COL_EDIT CHAR(1) DEFAULT 'Y' COMMENT '사용자_입력가능여부'
) COMMENT = '게시판설정_커스텀_컬럼_타입';
CREATE UNIQUE INDEX PK_mc_board_column_u ON mc_board_column (ORDER_NUM ASC);
ALTER TABLE mc_board_column ADD CONSTRAINT PK_mc_board_column PRIMARY KEY (ORDER_NUM);


/* 관리자_로그인_이력 */
CREATE TABLE mc_staff_login_tracking (
	SEQ NUMERIC(11) NOT NULL COMMENT '로그인_시퀀스',
	MEMBER_ID VARCHAR(100) COMMENT '회원_ID',
	MEMBER_NAME VARCHAR(100) COMMENT '회원이름',
	LOGIN_DATE DATETIME COMMENT '로그인일',
	LOGIN_IP VARCHAR(50) COMMENT '로그인_아이피'
) COMMENT = '관리자_로그인_이력';
CREATE UNIQUE INDEX PRIMARY10 ON mc_staff_login_tracking (SEQ);
CREATE INDEX SEQ ON mc_staff_login_tracking (SEQ, LOGIN_DATE);
ALTER TABLE mc_staff_login_tracking ADD CONSTRAINT PRIMARY_KEY10 PRIMARY KEY (SEQ);


/* 설문조사_질문지 */
CREATE TABLE mc_poll_question (
	POLL_SEQ NUMERIC(11) NOT NULL COMMENT '설문조사_시퀀스',
	QUESTION_SEQ NUMERIC(11) NOT NULL COMMENT '질문_시퀀스',
	QUESTION VARCHAR(500) NOT NULL COMMENT '질문',
	QUESTION_TYPE CHAR(1) NOT NULL COMMENT '질문_타입',
	QUESTION_CONTENT CLOB COMMENT '질문_내용',
	DEL_YN CHAR(1) NOT NULL COMMENT '삭제여부',
	SUBJECT_YN CHAR(1) DEFAULT 'N' COMMENT '소제목_여부',
	REQUIRED_YN CHAR(1) DEFAULT 'N' COMMENT '필수_여부',
	REQUIRED_COUNT NUMERIC(11) DEFAULT 0 COMMENT '다중선택_갯수',
	REQUIRED_COUNT_CONTROLL CHAR(1) DEFAULT 'U' COMMENT '다중선택_미만_이상_선택'
) COMMENT = '설문조사_질문지';
CREATE UNIQUE INDEX PK_mc_poll_question_u ON mc_poll_question (POLL_SEQ ASC, QUESTION_SEQ ASC);
ALTER TABLE mc_poll_question ADD CONSTRAINT PK_mc_poll_question PRIMARY KEY (POLL_SEQ, QUESTION_SEQ);


/* 게시판설정_카테고리 */
CREATE TABLE mc_board_cat (
	BOARD_CAT_SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	BOARD_SEQ NUMERIC(11) NOT NULL COMMENT '게시판_시퀀스',
	CAT_NM VARCHAR(64) NOT NULL COMMENT '카테고리명',
	REG_DT DATETIME COMMENT '등록일',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(32) NOT NULL COMMENT '등록자',
	MOD_DT DATETIME COMMENT '수정일',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제여부'
) COMMENT = '게시판설정_카테고리';
CREATE UNIQUE INDEX PRIMARY11 ON mc_board_cat (BOARD_CAT_SEQ, BOARD_SEQ ASC);
ALTER TABLE mc_board_cat ADD CONSTRAINT PRIMARY_KEY11 PRIMARY KEY (BOARD_CAT_SEQ, BOARD_SEQ);


/* 관리자_작업이력 */
CREATE TABLE mc_staff_location_tracking (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	PARENT_SEQ NUMERIC(11) NOT NULL COMMENT '로그인_시퀀스',
	LOCATION_TIME DATETIME COMMENT '이동시간',
	TITLE VARCHAR(500) COMMENT '메뉴명',
	URL VARCHAR(1000) NOT NULL COMMENT '이동주소',
	PARAMS CLOB COMMENT '파라미터목록',
	JOB VARCHAR(100) COMMENT '작업간략내용'
) COMMENT = '관리자_작업이력';
CREATE UNIQUE INDEX PRIMARY12 ON mc_staff_location_tracking (SEQ);
CREATE INDEX SEQ2 ON mc_staff_location_tracking (SEQ, PARENT_SEQ);
ALTER TABLE mc_staff_location_tracking ADD CONSTRAINT PRIMARY_KEY12 PRIMARY KEY (SEQ);


/* 메일발송_대기목록 */
CREATE TABLE mc_mail_queue (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	P_SEQ NUMERIC(11) NOT NULL COMMENT '메일발송_시퀀스',
	USER_NAME VARCHAR(50) NOT NULL COMMENT '수신자',
	USER_EMAIL VARCHAR(50) NOT NULL COMMENT '수신자_이메일',
	STATUS CHAR(1) COMMENT '상태'
) COMMENT = '메일발송_대기목록';
CREATE UNIQUE INDEX PRIMARY13 ON mc_mail_queue (SEQ);
ALTER TABLE mc_mail_queue ADD CONSTRAINT PRIMARY_KEY13 PRIMARY KEY (SEQ);


/* 소셜댓글_계정 */
CREATE TABLE mc_comment_sns_account (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	TWT_CONSUMER_KEY VARCHAR(255) COMMENT '트위터_컨서머_키',
	TWT_CONSUMER_SECRET VARCHAR(255) COMMENT '트위터_컨서머_시크릿',
	FACE_APPID VARCHAR(255) COMMENT '페이스북_앱_아이디',
	FACE_APP_SECRET VARCHAR(255) COMMENT '페이스북_앱_시크릿',
	FACE_ACCESS_TOKEN VARCHAR(255) COMMENT '페이스북_엑세스토큰',
	NAV_CLIENT_ID VARCHAR(255) COMMENT '네이버_클라이언트_아이디',
	NAV_CLIENT_SECRET VARCHAR(255) COMMENT '네이버_클라이언트_시크릿',
	GOOGLE_CLIENT_ID VARCHAR(255) COMMENT '구글_클라이언트_아이디',
	GOOGLE_CLIENT_SECRET VARCHAR(255) COMMENT '구글_클라이언트_시크릿',
	INSTA_CLIENT_ID VARCHAR(255) COMMENT '인스타_클라이언트_아이디',
	INSTA_CLIENT_SECRET VARCHAR(255) COMMENT '인스타_클라이언트_시크릿',
	KAO_CLIENT_ID VARCHAR(255) COMMENT '카카오_클라이언트_아이디'
) COMMENT = '소셜댓글_계정';
CREATE UNIQUE INDEX PRIMARY14 ON mc_comment_sns_account (SEQ);
ALTER TABLE mc_comment_sns_account ADD CONSTRAINT PRIMARY_KEY14 PRIMARY KEY (SEQ);

/* 메일서버설정 */
CREATE TABLE mc_mail_smtp (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	TITLE VARCHAR(200) NOT NULL COMMENT '호스트명',
	HOST VARCHAR(100) NOT NULL COMMENT '호스트',
	PORT NUMERIC(11) NOT NULL COMMENT '포트',
	AUTH_ID VARCHAR(200) NOT NULL COMMENT '인증_ID',
	AUTH_PW VARCHAR(200) NOT NULL COMMENT '인증_PW',
	SSL_YN VARCHAR(2) NOT NULL COMMENT 'SSL_YN',
	TLS_YN VARCHAR(2) NOT NULL COMMENT 'TLS_YN'
) COMMENT = '메일서버설정';
CREATE UNIQUE INDEX PRIMARY15 ON mc_mail_smtp (SEQ);
ALTER TABLE mc_mail_smtp ADD CONSTRAINT PRIMARY_KEY15 PRIMARY KEY (SEQ);


/* 게시판설정_목록 */
CREATE TABLE mc_board (
	BOARD_SEQ NUMERIC(11) NOT NULL COMMENT '게시판_시퀀스',
	BOARD_NM VARCHAR(64) NOT NULL COMMENT '게시판명',
	BOARD_TYPE VARCHAR(2) NOT NULL COMMENT '게시판_타입',
	COMMENT_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '댓글여부',
	COMMENT_TARGET CHAR(1) DEFAULT 'U' NOT NULL COMMENT '댓글지원대상',
	FILE_YN CHAR(1) NOT NULL COMMENT '파일첨부여부',
	LIMIT_FILE_SIZE NUMERIC(11) COMMENT '파일첨부_최대개수',
	FILE_LIMIT CHAR(1) DEFAULT 'N' NOT NULL COMMENT '파일첨부_최대용량',
	SEARCH_YN CHAR(1) NOT NULL COMMENT '검색노출여부',
	USE_YN CHAR(1) NOT NULL COMMENT '사용여부',
	CAT_YN CHAR(1) COMMENT '카테고리사용여부',
	REG_DT DATETIME COMMENT '등록일',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(32) NOT NULL COMMENT '등록자',
	MOD_DT DATETIME COMMENT '수정일',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제여부',
	SITE_ID NUMERIC(11) DEFAULT 1 COMMENT '사이트_ID',
	INSERT_YN CHAR(1) DEFAULT 'Y' COMMENT '사용자_글등록_사용여부',
	PUBLIC_YN CHAR(1) DEFAULT 'Y' NOT NULL COMMENT '비밀글_사용여부',
	THUMB_TYPE VARCHAR(30) DEFAULT 'TILE' COMMENT '리스트_형태',
	AGREE_YN CHAR(1) COMMENT '개인정보등록_사용여부',
	EDITOR_YN CHAR(1) COMMENT '에디터_사용여부',
	ROWS_TEXT VARCHAR(50) DEFAULT '10,20,30' COMMENT '리스트페이지에_보여줄_갯수목록',
	LIST_ROW VARCHAR(3) COMMENT '리스트페이지에_보여줄_갯수초기값',
	CCLNURI_YN CHAR(1) COMMENT '저작권보호_사용여부',
	TAG_YN CHAR(1) COMMENT '태그_사용여부'
) COMMENT = '게시판설정_목록';
CREATE UNIQUE INDEX PRIMARY16 ON mc_board (BOARD_SEQ);
ALTER TABLE mc_board ADD CONSTRAINT PRIMARY_KEY16 PRIMARY KEY (BOARD_SEQ);


/* 설문조사_결과 */
CREATE TABLE mc_poll_result (
	POLL_SEQ NUMERIC(11) NOT NULL COMMENT '설문조사_시퀀스',
	QUESTION_SEQ NUMERIC(11) NOT NULL COMMENT '질문지_시퀀스',
	ANSWER_SEQ NUMERIC(11) NOT NULL COMMENT '답변_시퀀스',
	ANSWER VARCHAR(126) NOT NULL COMMENT '답변',
	REG_DT DATETIME NOT NULL COMMENT '등록일',
	REG_ID VARCHAR(50) NOT NULL COMMENT '등록자_ID',
	REG_NM VARCHAR(32) NOT NULL COMMENT '등록자',
	REG_EMAIL VARCHAR(126) COMMENT '작성자_메일',
	REG_TEL VARCHAR(32) COMMENT '작성자_전화번호',
	REG_SEQ NUMERIC(11) NOT NULL COMMENT '작성_시퀀스',
	LOT_WIN CHAR(1) COMMENT '개인정보수집동의여부'
) COMMENT = '설문조사_결과';
CREATE INDEX PK_mc_poll_result_u ON mc_poll_result (POLL_SEQ ASC, QUESTION_SEQ ASC, ANSWER_SEQ ASC);


/* 관리자_허용아이피 */
CREATE TABLE mc_ip_allow (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	IP VARCHAR(100) COMMENT '아이피',
	TITLE VARCHAR(200) COMMENT '제목',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(32) COMMENT '등록자',
	REG_DT DATETIME COMMENT '등록일',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	MOD_DT DATETIME COMMENT '수정일',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL  COMMENT '삭제여부'
) COMMENT = '관리자_허용아이피';
CREATE UNIQUE INDEX PRIMARY17 ON mc_ip_allow (SEQ);
ALTER TABLE mc_ip_allow ADD CONSTRAINT PRIMARY_KEY17 PRIMARY KEY (SEQ);


/* 게시판설정_커스텀 */
CREATE TABLE mc_board_custom (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	BOARD_SEQ NUMERIC(11) NOT NULL COMMENT '게시판_시퀀스',
	ELEMENT VARCHAR(500) COMMENT '항목명',
	COLUMN_NAME VARCHAR(500) COMMENT '컬럼형태',
	USER_LIST_ELEMENT VARCHAR(500) COMMENT '사용자_리스트_설정',
	USER_LIST_COL VARCHAR(500) COMMENT '사용자_리스트_사이즈',
	USER_VIEW_ELEMENT VARCHAR(500) COMMENT '사용자_뷰_설정',
	USER_INSERT_ELEMENT VARCHAR(500) COMMENT '사용자_쓰기_설정',
	USER_MODIFY_ELEMENT VARCHAR(500) COMMENT '사용자_수정_설정',
	ADMIN_LIST_ELEMENT VARCHAR(500) COMMENT '관리자_리스트_설정',
	ADMIN_LIST_COL VARCHAR(500) COMMENT '관리자_리스트_사이즈',
	ADMIN_INSERT_ELEMENT VARCHAR(500) COMMENT '관리자_쓰기_설정',
	ADMIN_MODIFY_ELEMENT VARCHAR(500) COMMENT '관리자_수정_설정',
	REG_DT DATETIME COMMENT '등록일',
	REG_ID VARCHAR(50) COMMENT '등록자_ID',
	MOD_DT DATETIME COMMENT '수정일',
	MOD_ID VARCHAR(20) COMMENT '수정자_ID',
	DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
	ORDER_NUM NUMERIC(11) COMMENT '순서',
	require_yn CHAR(1) COMMENT '필수여부'
) COMMENT = '게시판설정_커스텀';
CREATE UNIQUE INDEX PRIMARY18 ON mc_board_custom (SEQ, BOARD_SEQ ASC);
ALTER TABLE mc_board_custom ADD CONSTRAINT PRIMARY_KEY18 PRIMARY KEY (SEQ, BOARD_SEQ);


/* 게시물_목록 */
CREATE TABLE mc_article (
	ARTICLE_SEQ NUMERIC(11) NOT NULL COMMENT '게시물_시퀀스',
	BOARD_SEQ NUMERIC(11) NOT NULL COMMENT '게시판_시퀀스',
	TITLE VARCHAR(256) NOT NULL COMMENT '제목',
	CONTS CLOB COMMENT '내용',
	IP VARCHAR(16) NOT NULL COMMENT '아이피',
	VIEW_CNT NUMERIC(11) DEFAULT 0 NOT NULL COMMENT '조회수',
	PUBLIC_YN CHAR(1) DEFAULT 'Y' NOT NULL COMMENT '공개여부',
	NOTICE_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '공지여부',
	CAT NUMERIC(11) COMMENT '카테고리_코드',
	STATE NUMERIC(11) COMMENT '상태값',
	THUMB VARCHAR(100) COMMENT '썸네일',
	PASSWORD VARCHAR(100) COMMENT '패스워드',
	REF_NUM NUMERIC(11) NOT NULL COMMENT '참조_시퀀스',
	STEP_NUM NUMERIC(11) DEFAULT 0 NOT NULL COMMENT '참조_시퀀스2',
	DEPTH_NUM NUMERIC(11) DEFAULT 0 NOT NULL COMMENT '계층_단계',
	SDATE DATETIME COMMENT '기타_시작일',
	EDATE DATETIME COMMENT '기타_종료일',
	REG_DT DATETIME COMMENT '등록일',
	REG_ID VARCHAR(30) NOT NULL COMMENT '등록자_ID',
	REG_NM VARCHAR(32) NOT NULL COMMENT '등록자',
	MOD_DT DATETIME COMMENT '수정일',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제여부',
	REPLY_CONTS CLOB COMMENT '답글',
	REPLY_ID VARCHAR(30) COMMENT '답글작성자_ID',
	REPLY_NM VARCHAR(32) COMMENT '답글작성자',
	REPLY_DT DATETIME COMMENT '답글작성일',
	TEL1 VARCHAR(4) COMMENT '전화번호1',
	TEL2 VARCHAR(4) COMMENT '전화번호2',
	TEL3 VARCHAR(4) COMMENT '전화번호3',
	CELL1 VARCHAR(4) COMMENT '휴대폰번호1',
	CELL2 VARCHAR(4) COMMENT '휴대폰번호2',
	CELL3 VARCHAR(4) COMMENT '휴대폰번호3',
	EMAIL1 VARCHAR(128) COMMENT '이메일1',
	EMAIL2 VARCHAR(128) COMMENT '이메일2',
	ETC01 VARCHAR(400) COMMENT '기타1',
	ETC02 VARCHAR(400) COMMENT '기타2',
	ETC03 VARCHAR(400) COMMENT '기타3',
	ETC04 VARCHAR(400) COMMENT '기타4',
	ETC05 VARCHAR(400) COMMENT '기타5',
	ETC06 VARCHAR(400) COMMENT '기타6',
	ETC07 VARCHAR(400) COMMENT '기타7',
	ETC08 VARCHAR(4000) COMMENT '기타8',
	ETC09 VARCHAR(4000) COMMENT '기타9',
	ETC10 VARCHAR(4000) COMMENT '기타10',
	CCL_TYPE CHAR(1) COMMENT '저작권보호_CCL',
	NURI_TYPE CHAR(1) COMMENT '저작권보호_공공누리',
	TAG_NAMES VARCHAR(200) COMMENT '태그'
) COMMENT = '게시물_목록';
CREATE UNIQUE INDEX PRIMARY19 ON mc_article (ARTICLE_SEQ, BOARD_SEQ ASC);
CREATE INDEX IDX_MC_ARTICLE ON mc_article (REF_NUM DESC, STEP_NUM ASC, DEPTH_NUM DESC, ARTICLE_SEQ ASC);
CREATE INDEX IDX_MC_ARTICLE01 ON mc_article (DEL_YN);
ALTER TABLE mc_article ADD CONSTRAINT PRIMARY_KEY19 PRIMARY KEY (ARTICLE_SEQ, BOARD_SEQ);

/* 게시판설정_상태 */
CREATE TABLE mc_board_state (
	BOARD_STATE_SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	BOARD_SEQ NUMERIC(11) NOT NULL COMMENT '게시판_시퀀스',
	STATE_NM VARCHAR(64) NOT NULL COMMENT '상태명',
	REG_DT DATETIME COMMENT '등록일',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(32) NOT NULL COMMENT '등록자',
	MOD_DT DATETIME COMMENT '수정일',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제여부'
) COMMENT = '게시판설정_상태';
CREATE UNIQUE INDEX PRIMARY20 ON mc_board_state (BOARD_STATE_SEQ, BOARD_SEQ ASC);
ALTER TABLE mc_board_state ADD CONSTRAINT PRIMARY_KEY20 PRIMARY KEY (BOARD_STATE_SEQ, BOARD_SEQ);


/* 소스수정_이력 */
CREATE TABLE mc_source_history (
	seq NUMERIC(11) NOT NULL COMMENT '시퀀스',
	file_path VARCHAR(200) COMMENT '파일경로',
	code_text CLOB COMMENT '코드내용',
	reg_nm VARCHAR(30) COMMENT '작성자',
	reg_id VARCHAR(30) COMMENT '작성자_ID',
	reg_dt DATETIME COMMENT '작성일'
) COMMENT = '소스수정_이력';
CREATE UNIQUE INDEX PRIMARY21 ON mc_source_history (seq);
ALTER TABLE mc_source_history ADD CONSTRAINT PRIMARY_KEY21 PRIMARY KEY (seq);


/* 메뉴별_컨텐츠_백업 */
CREATE TABLE mc_cms_content_bakup (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	CMS_MENU_SEQ NUMERIC(11) NOT NULL COMMENT '메뉴_시퀀스',
	CONTS CLOB COMMENT '내용',
	CMOD_ID VARCHAR(32) COMMENT '수정자_ID',
	CMOD_NM VARCHAR(32) COMMENT '수정자',
	CMOD_DT DATETIME COMMENT '수정일'
) COMMENT = '메뉴별_컨텐츠_백업';
CREATE UNIQUE INDEX PRIMARY22 ON mc_cms_content_bakup (SEQ);
ALTER TABLE mc_cms_content_bakup ADD CONSTRAINT PRIMARY_KEY22 PRIMARY KEY (SEQ);


/* 공통코드목록 */
CREATE TABLE mc_common_code_group (
	CODE_GROUP_SEQ NUMERIC(11) NOT NULL COMMENT '공통코드_시퀀스',
	GROUP_NM VARCHAR(64) NOT NULL COMMENT '공통코드명',
	CONTS VARCHAR(2000) COMMENT '내용',
	REG_ID VARCHAR(20) COMMENT '등록자_ID',
	REG_NM VARCHAR(20) COMMENT '등록자',
	REG_IP VARCHAR(15) COMMENT '등록자_IP',
	REG_DT DATETIME COMMENT '등록일',
	MOD_ID VARCHAR(20) COMMENT '수정자_ID',
	MOD_NM VARCHAR(20) COMMENT '수정자',
	MOD_IP VARCHAR(15) COMMENT '수정자_IP',
	MOD_DT DATETIME COMMENT '수정일',
	DEL_ID VARCHAR(20) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(20) COMMENT '삭제자',
	DEL_IP VARCHAR(15) COMMENT '삭제자_IP',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
) COMMENT = '공통코드목록';
CREATE UNIQUE INDEX PRIMARY23 ON mc_common_code_group (CODE_GROUP_SEQ);
ALTER TABLE mc_common_code_group ADD CONSTRAINT PRIMARY_KEY23 PRIMARY KEY (CODE_GROUP_SEQ);


/* 메뉴정보_백업 */
CREATE TABLE mc_cms_menu_bakup (
	SEQ NUMERIC(11) NOT NULL COMMENT '백업_시퀀스',
	CMS_MENU_SEQ NUMERIC(11) NOT NULL COMMENT '메뉴_시퀀스',
	PARENT_MENU_SEQ NUMERIC(11) COMMENT '부모키',
	TITLE VARCHAR(255) NOT NULL COMMENT '메뉴명',
	MENU_ORDER NUMERIC(11) DEFAULT 1 COMMENT '표시순서',
	USE_YN CHAR(1) DEFAULT 'Y' NOT NULL COMMENT '사용여부',
	BLANK_YN CHAR(1) DEFAULT 'N' COMMENT '새창여부',
	MENU_TYPE CHAR(1) COMMENT '메뉴타입',
	TARGET_URL VARCHAR(128) COMMENT '링크주소',
	PROGRAM_NM VARCHAR(255) COMMENT '프로그램명',
	BOARD_SEQ NUMERIC(11) COMMENT '게시판_번호',
	SITE_ID NUMERIC(11) DEFAULT 1 COMMENT '사이트_ID',
	REG_NM VARCHAR(32) COMMENT '등록자',
	REG_DT DATETIME COMMENT '등록일',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	MOD_DT DATETIME COMMENT '수정일',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
	CHILD_TYPE NUMERIC(11) COMMENT '자식타입',
	HEAD_HTML CLOB COMMENT '하단표시내용',
	TEMPLATE_TYPE NUMERIC(11) DEFAULT 1 COMMENT '템플릿_타입',
	MENU_URL VARCHAR(100) COMMENT '메뉴_URL',
	CUD_GROUP_SEQ VARCHAR(150) COMMENT '수정_삭제_권한시퀀스',
	R_GROUP_SEQ VARCHAR(150) COMMENT '읽기권한_시퀀스',
	MANAGE_URL VARCHAR(128) COMMENT '관리페이지_주소',
	TOP_YN CHAR(1) DEFAULT 'Y' COMMENT '상단메뉴_노출여부',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	INNER_YN CHAR(1) DEFAULT 'N' COMMENT '관리메뉴_탭에서_관리사용여부',
	SUB_PATH VARCHAR(20) COMMENT '위성 사이트사용시 서브패스',
	JSON_STAFFS CLOB COMMENT '메뉴관리자_목록',
	JSON_STAFF_GROUP CLOB COMMENT '메뉴관리자그룹_목록',
	JSON_LIBS CLOB COMMENT '추가JS파일_목록',
	ADD_PARAM VARCHAR(255) COMMENT '추가파라미터'
) COMMENT = '메뉴정보_백업';
CREATE UNIQUE INDEX PRIMARY24 ON mc_cms_menu_bakup (SEQ);
ALTER TABLE mc_cms_menu_bakup ADD CONSTRAINT PRIMARY_KEY24 PRIMARY KEY (SEQ);


/* 수신자_그룹상세 */
CREATE TABLE mc_mail_target_list (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	P_SEQ NUMERIC(11) NOT NULL COMMENT '수신자그룹_시퀀스',
	USER_NAME VARCHAR(50) NOT NULL COMMENT '수신자',
	USER_EMAIL VARCHAR(50) NOT NULL COMMENT '수신자_이메일'
) COMMENT = '수신자_그룹상세';
CREATE UNIQUE INDEX PRIMARY25 ON mc_mail_target_list (SEQ);
ALTER TABLE mc_mail_target_list ADD CONSTRAINT PRIMARY_KEY25 PRIMARY KEY (SEQ);


/* 게시판설정_커스텀_약관동의 */
CREATE TABLE mc_board_agree (
	BOARD_AGREE_SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	BOARD_SEQ NUMERIC(11) NOT NULL COMMENT '게시판_시퀀스',
	AGREE_TIT VARCHAR(256) COMMENT '약관명',
	AGREE_CONT CLOB COMMENT '약관내용',
	AGREE_CHECK CHAR(1) COMMENT '약광동의',
	AGREE_ORDER VARCHAR(3) COMMENT '약관순서',
	REG_DT DATETIME COMMENT '등록일',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(32) NOT NULL COMMENT '등록자',
	MOD_DT DATETIME COMMENT '수정일',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제여부'
) COMMENT = '게시판설정_커스텀_약관동의';
CREATE UNIQUE INDEX PRIMARY26 ON mc_board_agree (BOARD_AGREE_SEQ);
ALTER TABLE mc_board_agree ADD CONSTRAINT PRIMARY_KEY26 PRIMARY KEY (BOARD_AGREE_SEQ);


/* 페이지_조회수통계 */
CREATE TABLE mc_analytics (
	YMD CHAR(8) COMMENT '연월일',
	TITLE VARCHAR(100) NOT NULL COMMENT '메뉴명',
	REQUEST_URI VARCHAR(200) COMMENT '페이지_URL',
	QUERY_STRING VARCHAR(250) COMMENT '페이지_파라미터',
	BROWSER VARCHAR(250) COMMENT '브라우저',
	REFERER VARCHAR(250) COMMENT '이전주소',
	IP VARCHAR(15) COMMENT '아이피',
	LOCALE VARCHAR(10) COMMENT '지역',
	YYYY VARCHAR(4) COMMENT '연',
	MM CHAR(2) COMMENT '월',
	DD CHAR(2) COMMENT '일',
	HH CHAR(2) COMMENT '시',
	MEMBER_ID VARCHAR(30) COMMENT '회원_ID',
	SESSION_ID VARCHAR(40) COMMENT '세션_ID',
	CNT NUMERIC(11) DEFAULT 1 COMMENT '페이지뷰수',
	OS VARCHAR(20) COMMENT 'OS',
	SITE_ID NUMERIC(11) COMMENT '사이트_ID'
) COMMENT = '페이지_조회수통계';
CREATE INDEX IDX_MC_ANALYTICS ON mc_analytics (YMD);


/* 사용자회원_변경이력 */
CREATE TABLE mc_member_history (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	MEMBER_ID VARCHAR(30) COMMENT '회원_ID',
	MEMBER_NM VARCHAR(30) COMMENT '회원명',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(30) COMMENT '수정자',
	MOD_DT DATETIME COMMENT '수정일',
	CONTS VARCHAR(2000) COMMENT '변경내용',
	MOD_IP VARCHAR(16) COMMENT '수정자_IP'
) COMMENT = '관리자회원_변경이력';
CREATE UNIQUE INDEX PRIMARY27 ON mc_member_history (SEQ);
ALTER TABLE mc_member_history ADD CONSTRAINT PRIMARY_KEY27 PRIMARY KEY (SEQ);

/* 사용자회원_변경이력 */
CREATE TABLE mc_user_member_history (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	MEMBER_ID VARCHAR(30) COMMENT '회원_ID',
	MEMBER_NM VARCHAR(30) COMMENT '회원명',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(30) COMMENT '수정자',
	MOD_DT DATETIME COMMENT '수정일',
	CONTS VARCHAR(2000) COMMENT '변경내용',
	MOD_IP VARCHAR(16) COMMENT '수정자_IP'
) COMMENT = '사용자회원_변경이력';
CREATE UNIQUE INDEX PRIMARY47 ON mc_member_history (SEQ);
ALTER TABLE mc_user_member_history ADD CONSTRAINT PRIMARY_KEY47 PRIMARY KEY (SEQ);


/* 메일양식 */
CREATE TABLE mc_mail_form (
	SEQ NUMERIC(11) NOT NULL COMMENT '메일양식_시퀀스',
	TITLE VARCHAR(100) NOT NULL COMMENT '메일양식명',
	CONTS CLOB COMMENT '메일양식내용'
) COMMENT = '메일양식';
CREATE UNIQUE INDEX PRIMARY28 ON mc_mail_form (SEQ);
ALTER TABLE mc_mail_form ADD CONSTRAINT PRIMARY_KEY28 PRIMARY KEY (SEQ);


/* 개인정보_필터설정 */
CREATE TABLE mc_cms_menu_filter_def (
	SITE_ID NUMERIC(11) DEFAULT 0 NOT NULL COMMENT '사이트_ID',
	JUMIN_YN CHAR(1) DEFAULT 'N' COMMENT '주민번호_YN',
	BUSINO_YN CHAR(1) DEFAULT 'N' COMMENT '사업자_YN',
	BUBINO_YN CHAR(1) DEFAULT 'N' COMMENT '법인_YN',
	EMAIL_YN CHAR(1) DEFAULT 'N' COMMENT '이메일_YN',
	TEL_YN CHAR(1) DEFAULT 'N' COMMENT '전화번호_YN',
	CELL_YN CHAR(1) DEFAULT 'N' COMMENT '휴대폰_YN',
	CARD_YN CHAR(1) DEFAULT 'N' COMMENT '카드_YN',
	FORBIDDEN_WORD VARCHAR(4000) COMMENT '비속어'
) COMMENT = '개인정보_필터설정';
CREATE UNIQUE INDEX PRIMARY29 ON mc_cms_menu_filter_def (SITE_ID);
ALTER TABLE mc_cms_menu_filter_def ADD CONSTRAINT PRIMARY_KEY29 PRIMARY KEY (SITE_ID);


/* 프로그램목록 */
CREATE TABLE mc_programs (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	PROGRAM_NM VARCHAR(100) COMMENT '프로그램명',
	URL VARCHAR(200) COMMENT '프로그램_URL',
	MANAGE_URL VARCHAR(200) COMMENT '프로그램관리_URL',
	INNER_YN CHAR(1) COMMENT '프로그램관리_사용여부',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(32) COMMENT '등록자',
	REG_DT DATETIME COMMENT '등록일',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	MOD_DT DATETIME COMMENT '수정일',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제여부'
) COMMENT = '프로그램목록';
CREATE UNIQUE INDEX PRIMARY30 ON mc_programs (SEQ);
ALTER TABLE mc_programs ADD CONSTRAINT PRIMARY_KEY30 PRIMARY KEY (SEQ);


/* 레이아웃_설정 */
CREATE TABLE mc_layout_detail (
	PARENT_SEQ NUMERIC(11) COMMENT '레이아웃_시퀀스',
	IDX NUMERIC(11) COMMENT '정렬순서',
	COM_TYPE NUMERIC(11) COMMENT '타입',
	TAB_TITLE VARCHAR(100) COMMENT '탭 제목',
	CONTS CLOB COMMENT '내용',
	BOARD_SEQ NUMERIC(11) COMMENT '게시판 번호',
	BOARD_SEQS VARCHAR(100) COMMENT '게시판 번호(복합)',
	CNT NUMERIC(11) COMMENT '건수',
	LINK_URL VARCHAR(100) COMMENT '바로가기페이지'
) COMMENT = '레이아웃_설정';


/* 설문조사 */
CREATE TABLE mc_poll (
	POLL_SEQ NUMERIC(11) NOT NULL COMMENT '설문조사_시퀀스',
	TITLE VARCHAR(500) NOT NULL COMMENT '제목',
	CONTENT CLOB COMMENT '내용',
	START_DT DATETIME NOT NULL COMMENT '시작일',
	END_DT DATETIME NOT NULL COMMENT '종료일',
	REG_ID VARCHAR(50) NOT NULL COMMENT '등록자_ID',
	REG_NM VARCHAR(32) NOT NULL COMMENT '등록자',
	REG_DT DATETIME NOT NULL COMMENT '등록일',
	MOD_ID VARCHAR(50) COMMENT '수정자_ID',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	MOD_DT DATETIME COMMENT '수정일',
	DEL_ID VARCHAR(50) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_YN CHAR(1) NOT NULL COMMENT '삭제여부',
	USE_YN CHAR(1) NOT NULL COMMENT '사용여부',
	LOT_YN CHAR(1) NOT NULL COMMENT '개인정보_수집여부',
	CMS_MENU_SEQ NUMERIC(11) NOT NULL COMMENT '메뉴_시퀀스',
	CUD_GROUP_SEQ VARCHAR(150) COMMENT '설문대상_시퀀스',
	DUP_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '중복설문_가능여부'
) COMMENT = '설문조사';
CREATE UNIQUE INDEX PRIMARY31 ON mc_poll (POLL_SEQ);
ALTER TABLE mc_poll ADD CONSTRAINT PRIMARY_KEY31 PRIMARY KEY (POLL_SEQ);


/* 수신자_그룹 */
CREATE TABLE mc_mail_target (
	SEQ NUMERIC(11) NOT NULL COMMENT '수신자그룹_시퀀스',
	TITLE VARCHAR(100) NOT NULL COMMENT '수신자그룹명',
	TARGET_CNT NUMERIC(11) COMMENT '수신자수'
) COMMENT = '수신자_그룹';
CREATE UNIQUE INDEX PRIMARY32 ON mc_mail_target (SEQ);
ALTER TABLE mc_mail_target ADD CONSTRAINT PRIMARY_KEY32 PRIMARY KEY (SEQ);


/* 메뉴설정권한회원 */
CREATE TABLE mc_cms_permission (
	CMS_STAFF_SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	CMS_MENU_SEQ NUMERIC(11) NOT NULL COMMENT '메뉴_시퀀스',
	GROUP_SEQ NUMERIC(11) NOT NULL COMMENT '그룹_시퀀스',
	GROUP_NM VARCHAR(32) COMMENT '그룹명',
	MEMBER_NM VARCHAR(30) COMMENT '회원명',
	MEMBER_ID VARCHAR(30) COMMENT '회원_ID',
	REG_DT DATETIME COMMENT '등록일',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(30) COMMENT '등록자',
	ORDER_SEQ NUMERIC(11) DEFAULT 1 COMMENT '순서'
) COMMENT = '메뉴설정권한회원';
CREATE UNIQUE INDEX PRIMARY33 ON mc_cms_permission (CMS_STAFF_SEQ);
ALTER TABLE mc_cms_permission ADD CONSTRAINT PRIMARY_KEY33 PRIMARY KEY (CMS_STAFF_SEQ);


/* 첨부파일 */
CREATE TABLE mc_attach (
	UUID VARCHAR(50) NOT NULL COMMENT '고유번호',
	ATTACH_NM VARCHAR(256) NOT NULL COMMENT '파일명',
	YYYY CHAR(4) NOT NULL COMMENT '연',
	MM CHAR(2) DEFAULT '00' NOT NULL COMMENT '월',
	ORDER_SEQ NUMERIC(11) COMMENT '순서',
	TABLE_NM VARCHAR(64) COMMENT '구분값',
	TABLE_SEQ NUMERIC(11) COMMENT '게시물_시퀀스',
	REG_ID VARCHAR(30) NOT NULL COMMENT '등록자_ID',
	REG_NM VARCHAR(32) NOT NULL COMMENT '등록자',
	REG_DT DATETIME COMMENT '등록일',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제여부',
	VIEW_CNT NUMERIC(11) DEFAULT 0 COMMENT '조회수'
) COMMENT = '첨부파일';
CREATE UNIQUE INDEX PRIMARY34 ON mc_attach (UUID);
CREATE INDEX IDX_MC_ATTACH ON MC_ATTACH(TABLE_SEQ, TABLE_NM, UUID);
ALTER TABLE mc_attach ADD CONSTRAINT PRIMARY_KEY34 PRIMARY KEY (UUID);


/* 메뉴별_개인정보_결과 */
CREATE TABLE mc_personal_data (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	CMS_MENU_SEQ NUMERIC(11) COMMENT '메뉴_시퀀스',
	SITE_ID NUMERIC(11) COMMENT '사이트_ID',
	SUB_SEQ NUMERIC(11) COMMENT '보조_시퀀스',
	MENU_NM VARCHAR(255) NOT NULL COMMENT '메뉴명',
	TITLE VARCHAR(200) COMMENT '제목',
	REG_DT DATETIME COMMENT '등록일',
	JUMIN_CNT NUMERIC(11) DEFAULT 0 COMMENT '주민번호_건수',
	JUMIN_CONTS CLOB COMMENT '주민번호_상세',
	BUSINO_CNT NUMERIC(11) DEFAULT 0 COMMENT '사업자번호_건수',
	BUSINO_CONTS CLOB COMMENT '사업자번호_상세',
	BUBINO_CNT NUMERIC(11) DEFAULT 0 COMMENT '법인번호_건수',
	BUBINO_CONTS CLOB COMMENT '법인번호_상세',
	EMAIL_CNT NUMERIC(11) DEFAULT 0 COMMENT '이메일_건수',
	EMAIL_CONTS CLOB COMMENT '이메일_상세',
	CELL_CNT NUMERIC(11) DEFAULT 0 COMMENT '휴대폰_건수',
	CELL_CONTS CLOB COMMENT '휴대폰_상세',
	TEL_CNT NUMERIC(11) DEFAULT 0 COMMENT '전화번호_건수',
	TEL_CONTS CLOB COMMENT '전화번호_상세',
	CARD_CNT NUMERIC(11) DEFAULT 0 COMMENT '카드_건수',
	CARD_CONTS CLOB COMMENT '카드_상세'
) COMMENT = '메뉴별_개인정보_결과';
CREATE UNIQUE INDEX PRIMARY35 ON mc_personal_data (SEQ);
ALTER TABLE mc_personal_data ADD CONSTRAINT PRIMARY_KEY35 PRIMARY KEY (SEQ);


/* 게시판_타입 */
CREATE TABLE mc_board_list (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	BOARD_TYPE VARCHAR(2) NOT NULL COMMENT '게시판_타입',
	NAME VARCHAR(50) COMMENT '게시판_타입명'
) COMMENT = '게시판_타입';
CREATE UNIQUE INDEX PRIMARY36 ON mc_board_list (SEQ ASC);
ALTER TABLE mc_board_list ADD CONSTRAINT PRIMARY_KEY36 PRIMARY KEY (SEQ);


/* 휴일관리 */
CREATE TABLE mc_holiday (
	HOLIDAY_SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	HOLIDAY VARCHAR(30) COMMENT '휴일',
	TITLE VARCHAR(32) COMMENT '제목',
	LUNAR_CAL VARCHAR(30) COMMENT '음력',
	SUN_CAL VARCHAR(30) COMMENT '양력',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(32) COMMENT '등록자',
	REG_DT DATETIME COMMENT '등록일',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	MOD_DT DATETIME COMMENT '수정일',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제여부'
) COMMENT = '휴일관리';
CREATE UNIQUE INDEX PRIMARY37 ON mc_holiday (HOLIDAY_SEQ);
ALTER TABLE mc_holiday ADD CONSTRAINT PRIMARY_KEY37 PRIMARY KEY (HOLIDAY_SEQ);


/* 메일발송목록 */
CREATE TABLE mc_mail (
	SEQ NUMERIC(11) NOT NULL COMMENT '메일발송_시퀀스',
	TITLE VARCHAR(200) NOT NULL COMMENT '제목',
	CONTS CLOB COMMENT '내용',
	SENDER_NM VARCHAR(200) NOT NULL COMMENT '보내는사람',
	SENDER_MAIL VARCHAR(200) NOT NULL COMMENT '보내는사람_이메일',
	STATUS VARCHAR(2) NOT NULL COMMENT '상태',
	REG_ID VARCHAR(50) NOT NULL COMMENT '등록자_ID',
	REG_NM VARCHAR(32) NOT NULL COMMENT '등록자',
	REG_DT DATETIME COMMENT '등록일',
	MOD_ID VARCHAR(50) COMMENT '수정자_ID',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	MOD_DT DATETIME COMMENT '수정일',
	TARGET_SEQ NUMERIC(11) COMMENT '수신자그룹_시퀀스',
	FORM_SEQ NUMERIC(11) COMMENT '메일양식_시퀀스'
) COMMENT = '메일발송목록';
CREATE UNIQUE INDEX PRIMARY38 ON mc_mail (SEQ);
ALTER TABLE mc_mail ADD CONSTRAINT PRIMARY_KEY38 PRIMARY KEY (SEQ);


/* 예약등록 */
CREATE TABLE mc_reserve (
	RESERVE_SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	SITE_ID NUMERIC(11) COMMENT '사이트_ID',
	CMS_MENU_SEQ NUMERIC(11) COMMENT '메뉴_시퀀스',
	ARTICLE_SEQ NUMERIC(11) COMMENT '게시물_시퀀스',
	PARAMS CLOB COMMENT '파라미터셋',
	RESERVE_DT VARCHAR(30) COMMENT '예약배포일',
	TYPE VARCHAR(3) COMMENT '배포타입',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(32) COMMENT '등록자',
	REG_DT DATETIME COMMENT '등록일',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
	TITLE VARCHAR(100) COMMENT '제목',
	GUBUN VARCHAR(1) DEFAULT 'M' COMMENT '구분',
	BOARD_SEQ NUMERIC(11) COMMENT '게시물_시퀀스',
	STATUS CHAR(1) DEFAULT 'I' COMMENT '상태'
) COMMENT = '예약등록';
CREATE UNIQUE INDEX PRIMARY39 ON mc_reserve (RESERVE_SEQ);
ALTER TABLE mc_reserve ADD CONSTRAINT PRIMARY_KEY39 PRIMARY KEY (RESERVE_SEQ);


/* JS_CSS_파일목록 */
CREATE TABLE mc_cms_menu_libs (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	CMS_MENU_SEQ NUMERIC(11) COMMENT '메뉴_시퀀스',
	TP CHAR(1) COMMENT '파일타입',
	EXTENSION VARCHAR(3) COMMENT '확장자명',
	ORDER_SEQ NUMERIC(11) COMMENT '순서',
	FULL_PATH VARCHAR(200) COMMENT '전체경로',
	ORG_FILE_NAME VARCHAR(50) COMMENT '원본파일명',
	SYS_FILE_NAME VARCHAR(50) COMMENT '시스템파일명'
) COMMENT = 'JS_CSS_파일목록';
CREATE UNIQUE INDEX PRIMARY40 ON mc_cms_menu_libs (SEQ);
ALTER TABLE mc_cms_menu_libs ADD CONSTRAINT PRIMARY_KEY40 PRIMARY KEY (SEQ);


/* 사이트_기본설정 */
CREATE TABLE mc_basic_setting (
	site_id NUMERIC(11) COMMENT '사이트아이디',
	certification_yn CHAR(1) COMMENT '회원가입 본인인증사용여부',
	logout_time_yn CHAR(1) COMMENT '로그아웃시간 사용여부',
	logout_time NUMERIC(11) COMMENT '로그아웃시간 분',
	pw_change_yn CHAR(1) COMMENT '비밀번호변경주기 사용여부',
	pw_change_cycle NUMERIC(11) COMMENT '비밀번호변경주기 개월',
	dormancy_yn CHAR(1) COMMENT '장기 미접속 사용여부',
	dormancy_day NUMERIC(11) COMMENT '장기 미접속 설정개월',
	adm_logout_time_yn CHAR(1) COMMENT '관리자 로그아웃시간 사용여부',
	adm_logout_time NUMERIC(11) COMMENT '관리자 로그아웃시간 분',
	adm_pw_change_yn CHAR(1) COMMENT '관리자 비밀번호변경주기 사용여부',
	adm_pw_change_cycle NUMERIC(11) COMMENT '관리자 비밀번호변경주기 개월',
	adm_dormancy_yn CHAR(1) COMMENT '관리자 장기 미접속 사용여부',
	adm_dormancy_day NUMERIC(11) COMMENT '관리자 장기 미접속 설정개월'
) COMMENT = '사이트_기본설정';


/* 설문조사_응답보기 */
CREATE TABLE mc_poll_answer (
	POLL_SEQ NUMERIC(11) NOT NULL COMMENT '설문조사_시퀀스',
	QUESTION_SEQ NUMERIC(11) NOT NULL COMMENT '질문_시퀀스',
	ANSWER_SEQ NUMERIC(11) NOT NULL COMMENT '답변_시퀀스',
	ANSWER VARCHAR(126) NOT NULL COMMENT '답변',
	NULL_CHK CHAR(1) COMMENT '널_체크',
	JUMP_CHK CHAR(1) COMMENT '건너띄기_체크',
	DEL_YN CHAR(1) NOT NULL COMMENT '삭제여부'
) COMMENT = '설문조사_응답보기';
CREATE UNIQUE INDEX PK_mc_poll_answer_u ON mc_poll_answer (POLL_SEQ ASC, QUESTION_SEQ ASC, ANSWER_SEQ ASC);
ALTER TABLE mc_poll_answer ADD CONSTRAINT PK_mc_poll_answer PRIMARY KEY (POLL_SEQ, QUESTION_SEQ, ANSWER_SEQ);


/* 게시물_댓글 */
CREATE TABLE mc_comment_sns (
	COMMENT_SEQ NUMERIC(11) NOT NULL COMMENT '고유번호',
	CMS_MENU_SEQ NUMERIC(11) NOT NULL COMMENT '메뉴번호',
	ARTICLE_SEQ NUMERIC(11) NOT NULL COMMENT '게시물번호',
	PARENT_SEQ NUMERIC(11) COMMENT '부모키',
	CONTS VARCHAR(3000) NOT NULL COMMENT '내용',
	IP VARCHAR(16) NOT NULL COMMENT '아이피',
	REG_DT DATETIME NOT NULL COMMENT '등록일',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(32) NOT NULL COMMENT '등록자',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제여부',
	TWT_YN CHAR(1) DEFAULT 'N' COMMENT '트위터 보냄',
	FACE_YN CHAR(1) DEFAULT 'N' COMMENT '페이스북 보냄',
	BLOG_YN CHAR(1) DEFAULT 'N' COMMENT '블로그 보냄',
	PROFILE_IMG VARCHAR(300) COMMENT '프로필 주소',
	MAIN_ACCOUNT VARCHAR(30) COMMENT '로그인한 계정',
	KAO_YN CHAR(1) DEFAULT 'N' COMMENT '카카오 보냄',
	SNS_LINK VARCHAR(100) COMMENT 'SNS링크'
) COMMENT = '게시물_댓글';
CREATE UNIQUE INDEX PRIMARY41 ON mc_comment_sns (COMMENT_SEQ);
CREATE INDEX IDX_MC_COMMENT_SNS ON MC_COMMENT_SNS(ARTICLE_SEQ, CMS_MENU_SEQ);
ALTER TABLE mc_comment_sns ADD CONSTRAINT PRIMARY_KEY41 PRIMARY KEY (COMMENT_SEQ);


/* 메인_레이아웃설정 */
CREATE TABLE mc_layout (
	SEQ NUMERIC(11) NOT NULL COMMENT '레이아웃_시퀀스',
	SITE_ID NUMERIC(11) COMMENT '사이트_ID',
	IDX NUMERIC(11) COMMENT '정렬순서',
	COL_CNT NUMERIC(11) COMMENT '가로사이즈',
	ROW_CNT NUMERIC(11) COMMENT '세로사이즈',
	TITLE VARCHAR(100) COMMENT '제목',
	TAB_YN CHAR(1) DEFAULT 'N' COMMENT '탭_사용여부'
) COMMENT = '메인_레이아웃설정';
CREATE UNIQUE INDEX PRIMARY42 ON mc_layout (SEQ);
ALTER TABLE mc_layout ADD CONSTRAINT PRIMARY_KEY42 PRIMARY KEY (SEQ);


/* 관리자그룹 */
CREATE TABLE mc_group (
	GROUP_SEQ NUMERIC(11) NOT NULL COMMENT '그룹_시퀀스',
	GROUP_NM VARCHAR(32) NOT NULL COMMENT '그룹명',
	PARENT_SEQ NUMERIC(11) COMMENT '부모그룹_시퀀스',
	USE_YN CHAR(1) DEFAULT 'Y' NOT NULL COMMENT '사용여부',
	REG_DT DATETIME NOT NULL COMMENT '등록일',
	MOD_DT DATETIME COMMENT '수정일',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제여부',
	ORDER_SEQ NUMERIC(11) DEFAULT 1 NOT NULL COMMENT '순서',
	REG_NM VARCHAR(32) COMMENT '등록자',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	TEL VARCHAR(13) COMMENT '전화번호',
	FAX VARCHAR(13) COMMENT '팩스번호',
	RESPONSIBILITIES VARCHAR(500) COMMENT '상세내용',
	MANAGE_SEQ NUMERIC(11) COMMENT '관리_시퀀스'
) COMMENT = '관리자그룹';
CREATE UNIQUE INDEX PRIMARY43 ON mc_group (GROUP_SEQ);
CREATE INDEX IDX_GROUP_SORTORDER ON mc_group (PARENT_SEQ, ORDER_SEQ);
ALTER TABLE mc_group ADD CONSTRAINT PRIMARY_KEY43 PRIMARY KEY (GROUP_SEQ);


/* 게시물_신고 */
CREATE TABLE mc_user_report (
	REPORT_SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	ARTICLE_SEQ NUMERIC(11) NOT NULL COMMENT '게시물_시퀀스',
	BOARD_SEQ NUMERIC(11) NOT NULL COMMENT '게시판_시퀀스',
	REPORTCONTS VARCHAR(4000) NOT NULL COMMENT '내용',
	IP VARCHAR(16) NOT NULL COMMENT '아이피',
	REG_DT DATETIME COMMENT '등록일',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(32) COMMENT '등록자'
) COMMENT = '게시물_신고';
CREATE UNIQUE INDEX PRIMARY44 ON mc_user_report (REPORT_SEQ);
CREATE INDEX IDX_MC_USER_REPORT ON MC_USER_REPORT(BOARD_SEQ, ARTICLE_SEQ);
ALTER TABLE mc_user_report ADD CONSTRAINT PRIMARY_KEY44 PRIMARY KEY (REPORT_SEQ);


/* 사용자회원 */
CREATE TABLE mc_user_member (
	MEMBER_ID VARCHAR(30) NOT NULL COMMENT '회원_ID',
	MEMBER_PW VARCHAR(100) COMMENT '회원_패스워드',
	MEMBER_NM VARCHAR(30) COMMENT '회원명',
	EMAIL VARCHAR(100) COMMENT '이메일',
	TEL VARCHAR(15) COMMENT '전화번호',
	CELL VARCHAR(15) COMMENT '휴대폰번호',
	GROUP_SEQ NUMERIC(11) COMMENT '그룹_시퀀스',
	LAST_LOGIN DATETIME COMMENT '마지막_로그인시간',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(30) COMMENT '수정자',
	MOD_DT DATETIME COMMENT '수정일',
	MOD_IP VARCHAR(16) COMMENT '수정자_IP',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	DEL_NM VARCHAR(30) COMMENT '삭제자',
	DEL_DT DATETIME COMMENT '삭제일',
	USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
	DEL_YN CHAR(1) DEFAULT 'N' COMMENT '삭제여부',
	ORDER_SEQ NUMERIC(11) COMMENT '순서',
	BLOCK_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '블록여부',
	LOGIN_FAIL_CNT NUMERIC(11) DEFAULT 0 NOT NULL COMMENT '로그인_시도횟수',
	LAST_PW_DT DATETIME COMMENT '마지막_패스워드변경일',
	DI VARCHAR(100) COMMENT 'DI',
	BIRTH VARCHAR(8) COMMENT '생년월일',
	EMAIL_YN CHAR(1) DEFAULT 'N' COMMENT '이메일발송_허용',
	SMS_YN CHAR(1) DEFAULT 'N' COMMENT 'SMS발송_허용',
	REG_DT DATETIME COMMENT '등록일',
	DORMANCY_YN CHAR(1) DEFAULT 'N' COMMENT '휴면계정_여부',
	LEAVE_CONT VARCHAR(1000) COMMENT '탈퇴_사유'
) COMMENT = '사용자회원';
CREATE UNIQUE INDEX PRIMARY45 ON mc_user_member (MEMBER_ID);
ALTER TABLE mc_user_member ADD CONSTRAINT PRIMARY_KEY45 PRIMARY KEY (MEMBER_ID);


/* 회원그룹 */
CREATE TABLE mc_user_group (
	GROUP_SEQ NUMERIC(11) NOT NULL COMMENT '그룹_시퀀스',
	GROUP_NM VARCHAR(32) NOT NULL COMMENT '그룹명',
	PARENT_SEQ NUMERIC(11) COMMENT '부모그룹_시퀀스',
	USE_YN CHAR(1) DEFAULT 'Y' NOT NULL COMMENT '사용여부',
	REG_DT DATETIME NOT NULL COMMENT '등록일',
	MOD_DT DATETIME COMMENT '수정일',
	DEL_DT DATETIME COMMENT '삭제일',
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL COMMENT '삭제여부',
	ORDER_SEQ NUMERIC(11) DEFAULT 1 NOT NULL COMMENT '순서',
	REG_NM VARCHAR(32) COMMENT '등록자',
	MOD_NM VARCHAR(32) COMMENT '수정자',
	DEL_NM VARCHAR(32) COMMENT '삭제자',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	DEL_ID VARCHAR(30) COMMENT '삭제자_ID',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	TEL VARCHAR(13) COMMENT '전화번호',
	FAX VARCHAR(13) COMMENT '팩스번호',
	RESPONSIBILITIES VARCHAR(500) COMMENT '상세내용',
	MANAGE_SEQ NUMERIC(11) COMMENT '관리_시퀀스'
) COMMENT = '회원그룹';
CREATE UNIQUE INDEX PRIMARY9 ON mc_user_group (GROUP_SEQ);
CREATE INDEX IDX_GROUP_SORTORDER2 ON mc_user_group (PARENT_SEQ, ORDER_SEQ);
ALTER TABLE mc_user_group ADD CONSTRAINT PRIMARY_KEY9 PRIMARY KEY (GROUP_SEQ);


/* 메뉴_그룹별_사용자_접근권한 */
CREATE TABLE mc_cms_menu_grant (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	CMS_MENU_SEQ NUMERIC(11) NOT NULL COMMENT '메뉴_시퀀스',
	GROUP_SEQ NUMERIC(11) NOT NULL COMMENT '그룹_시퀀스',
	GROUP_NM VARCHAR(32) COMMENT '그룹명',
	REG_DT DATETIME COMMENT '등록일',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(30) COMMENT '등록자',
	ORDER_SEQ NUMERIC(11) DEFAULT 1 COMMENT '순서'
) COMMENT = '메뉴_그룹별_사용자_접근권한';

CREATE UNIQUE INDEX PRIMARY46 ON mc_cms_menu_grant (SEQ);
ALTER TABLE mc_cms_menu_grant ADD CONSTRAINT PRIMARY_KEY46 PRIMARY KEY (SEQ);

/* 이력이남는_페이지 */
CREATE TABLE MC_PHISTORY (
	SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	GUBUN NUMERIC(11) COMMENT '구분',
	CONTS CLOB COMMENT '내용',
	REG_DT DATETIME COMMENT '등록일',
	REG_ID VARCHAR(30) COMMENT '등록자_ID',
	REG_NM VARCHAR(32) NOT NULL COMMENT '등록자',
	MOD_DT DATETIME COMMENT '수정일',
	MOD_ID VARCHAR(30) COMMENT '수정자_ID',
	MOD_NM VARCHAR(32) COMMENT '수정자'
);
CREATE UNIQUE INDEX PRIMARY48 ON MC_PHISTORY (SEQ);
ALTER TABLE MC_PHISTORY ADD CONSTRAINT PRIMARY_KEY48 PRIMARY KEY (SEQ);

/* 알림_읽음 */
CREATE TABLE MC_ALRAM_READ (
	TABLE_CD VARCHAR(50) NOT NULL COMMENT '테이블코드',
	ARTICLE_SEQ NUMERIC(11) NOT NULL COMMENT '시퀀스',
	MEMBER_ID VARCHAR(30) NOT NULL COMMENT '회원_ID',
	READ_DT DATETIME COMMENT '읽은날짜'
) COMMENT = '알림_읽음';
CREATE UNIQUE INDEX IDX_MC_ALRAM_READ ON MC_ALRAM_READ(TABLE_CD,ARTICLE_SEQ,MEMBER_ID);
ALTER TABLE MC_ALRAM_READ ADD CONSTRAINT PRIMARY_KEY49 PRIMARY KEY (TABLE_CD,ARTICLE_SEQ,MEMBER_ID);


ALTER TABLE mc_cms_staff_group ADD CONSTRAINT FK_mc_cms_menu_TO_mc_cms_staff_group FOREIGN KEY (CMS_MENU_SEQ) REFERENCES mc_cms_menu (CMS_MENU_SEQ);
ALTER TABLE mc_satisfaction ADD CONSTRAINT FK_mc_cms_mn_TO_mc_stsfctn FOREIGN KEY (CMS_MENU_SEQ) REFERENCES mc_cms_menu (CMS_MENU_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_common_code ADD CONSTRAINT FK_mc_cmn_grp_TO_mc_cmn_cd FOREIGN KEY (CODE_GROUP_SEQ) REFERENCES mc_common_code_group (CODE_GROUP_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_cms_staff ADD CONSTRAINT FK_mc_cms_menu_TO_mc_cms_staff FOREIGN KEY (CMS_MENU_SEQ) REFERENCES mc_cms_menu (CMS_MENU_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_poll_question ADD CONSTRAINT FK_mc_poll_TO_mc_poll_question FOREIGN KEY (POLL_SEQ) REFERENCES mc_poll (POLL_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_board_cat ADD CONSTRAINT FK_mc_board_TO_mc_board_cat FOREIGN KEY (BOARD_SEQ) REFERENCES mc_board (BOARD_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_staff_location_tracking ADD CONSTRAINT FK_mc_trckng_TO_mc FOREIGN KEY (PARENT_SEQ) REFERENCES mc_staff_login_tracking (SEQ) ON DELETE CASCADE;
ALTER TABLE mc_mail_queue ADD CONSTRAINT FK_mc_mail_TO_mc_mail_queue FOREIGN KEY (P_SEQ) REFERENCES mc_mail (SEQ) ON DELETE CASCADE;
ALTER TABLE mc_poll_result ADD CONSTRAINT FK_mc_poll_TO_mc_poll_result FOREIGN KEY (POLL_SEQ) REFERENCES mc_poll (POLL_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_board_custom ADD CONSTRAINT FK_mc_board_TO_mc_board_custom FOREIGN KEY (BOARD_SEQ) REFERENCES mc_board (BOARD_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_article ADD CONSTRAINT FK_mc_board_TO_mc_article FOREIGN KEY (BOARD_SEQ) REFERENCES mc_board (BOARD_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_board_state ADD CONSTRAINT FK_mc_board_TO_mc_board_state FOREIGN KEY (BOARD_SEQ) REFERENCES mc_board (BOARD_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_cms_content_bakup ADD CONSTRAINT FK_mc_mn_TO_mc_cntnt_bkp FOREIGN KEY (CMS_MENU_SEQ) REFERENCES mc_cms_menu (CMS_MENU_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_cms_menu_bakup ADD CONSTRAINT FK_mc_cms_mn_TO_mc_mn_bkp FOREIGN KEY (CMS_MENU_SEQ) REFERENCES mc_cms_menu (CMS_MENU_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_mail_target_list ADD CONSTRAINT FK_mc_trgt_TO_mc_trgt_lst FOREIGN KEY (P_SEQ) REFERENCES mc_mail_target (SEQ) ON DELETE CASCADE;
ALTER TABLE mc_board_agree ADD CONSTRAINT FK_mc_board_TO_mc_board_agree FOREIGN KEY (BOARD_SEQ) REFERENCES mc_board (BOARD_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_layout_detail ADD CONSTRAINT FK_mc_layout_TO_mc_lt_dtl FOREIGN KEY (PARENT_SEQ) REFERENCES mc_layout (SEQ) ON DELETE CASCADE;
ALTER TABLE mc_cms_permission ADD CONSTRAINT FK_mc_cms_mn_TO_mc_prmsn FOREIGN KEY (CMS_MENU_SEQ) REFERENCES mc_cms_menu (CMS_MENU_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_personal_data ADD CONSTRAINT FK_mc_cms_mn_TO_mc_prsnl_dt FOREIGN KEY (CMS_MENU_SEQ) REFERENCES mc_cms_menu (CMS_MENU_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_cms_menu_libs ADD CONSTRAINT FK_mc_cms_mn_TO_mc_mn_lbs FOREIGN KEY (CMS_MENU_SEQ) REFERENCES mc_cms_menu (CMS_MENU_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_poll_answer ADD CONSTRAINT FK_mc_poll_TO_mc_poll_answer FOREIGN KEY (POLL_SEQ) REFERENCES mc_poll (POLL_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_user_report ADD CONSTRAINT FK_mc_artcl_TO_mc_usr_rprt FOREIGN KEY (ARTICLE_SEQ, BOARD_SEQ) REFERENCES mc_article (ARTICLE_SEQ, BOARD_SEQ) ON DELETE CASCADE;
ALTER TABLE mc_cms_menu_grant ADD CONSTRAINT FK_mc_cms_menu_TO_mc_cms_menu_grant FOREIGN KEY (CMS_MENU_SEQ) REFERENCES mc_cms_menu (CMS_MENU_SEQ);


CREATE SERIAL SEQ_MC_CMS_MENU START WITH 8 MINVALUE 0 MAXVALUE 9223372036854775806;
CREATE SERIAL SEQ_MC_CMS_MENU_BAKUP NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_CMS_CONTENT_BAKUP NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_CMS_STAFF NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_CMS_PERMISSION NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_CMS_STAFF_GROUP NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_IP_ALLOW NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_COMMON_CODE_GROUP START WITH 5 MINVALUE 0 MAXVALUE 9223372036854775806;
CREATE SERIAL SEQ_MC_COMMON_CODE START WITH 41 MINVALUE 0 MAXVALUE 9223372036854775806;
CREATE SERIAL SEQ_MC_GROUP START WITH 3 MINVALUE 0 MAXVALUE 9223372036854775806;
CREATE SERIAL SEQ_MC_MEMBER_HISTORY NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_USER_MEMBER_HISTORY NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_PROGRAMS START WITH 100 MINVALUE 1 MAXVALUE 9223372036854775806;
CREATE SERIAL SEQ_MC_BOARD NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_BOARD_CAT NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_BOARD_STATE NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_USER_REPORT NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_ARTICLE NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_BOARD_LIST START WITH 7 MINVALUE 1 MAXVALUE 9223372036854775806;
CREATE SERIAL SEQ_MC_BOARD_CUSTOM NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_BOARD_AGREE NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_ARTICLE_COMMENT NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_COMMENT_SNS NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_POPUPZONE NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_RESERVE NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_SATISFACTION NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_HOLIDAY START WITH 518 MINVALUE 518 MAXVALUE 9223372036854775806;
CREATE SERIAL SEQ_MC_STAFF_LOGIN_TRACKING NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_STAFF_LOCATION_TRACKING NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_CMS_MENU_FILTER NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_PERSONAL_DATA NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_MAIL NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_MAIL_FORM NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_MAIL_QUEUE NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_MAIL_SMTP NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_MAIL_TARGET NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_MAIL_TARGET_LIST NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_CMS_MENU_LIBS NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_SOURCE_HISTORY NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_USER_GROUP START WITH 2 MINVALUE 2 NOMAXVALUE;
CREATE SERIAL SEQ_MC_CMS_MENU_GRANT NOMINVALUE NOMAXVALUE;
CREATE SERIAL SEQ_MC_PHISTORY NOMINVALUE NOMAXVALUE;


CREATE OR REPLACE FUNCTION FN_GET_SPLIT(
    IN_STR         IN  STRING,    
    IN_LEVEL       IN  NUMERIC,         
    IN_DELIMETER   IN  STRING,
    IN_DEFAULT_VAL IN  STRING     
)RETURN STRING
AS LANGUAGE JAVA NAME 'SpCubrid.fn_get_split(java.lang.String,int,java.lang.String,java.lang.String) return java.lang.String' COMMENT 'FN_GET_SPLIT';

CREATE  TRIGGER TR_MC_MEMBER
AFTER  UPDATE ON MC_MEMBER
		IF  NVL(old.EMAIL, 'x') !=  NVL(obj.EMAIL, 'x')  OR NVL(old.TEL, 'x') !=  NVL(obj.TEL, 'x')  OR NVL(old.CELL, 'x') !=  NVL(obj.CELL, 'x')  OR NVL(old.MEMBER_PW, 'x') !=  NVL(obj.MEMBER_PW, 'x')  OR NVL(old.GROUP_SEQ, -1) !=  NVL(obj.GROUP_SEQ, -1)
       EXECUTE  
       INSERT INTO MC_MEMBER_HISTORY(
	        SEQ, MEMBER_ID, MEMBER_NM, CONTS, MOD_ID, MOD_NM, MOD_DT, MOD_IP
	    ) VALUES(
	       SEQ_MC_MEMBER_HISTORY.NEXTVAL, obj.MEMBER_ID, obj.MEMBER_NM, '<p>이메일 : ' || obj.EMAIL || '</p><p>전화번호 : ' || old.TEL || '</p><p>휴대전화 : ' || old.CELL || '</p>', obj.MOD_ID,  obj.MOD_NM, obj.MOD_DT, obj.MOD_IP	      
	    );	   
	    
CREATE  TRIGGER TR_MC_USER_MEMBER
AFTER  UPDATE ON MC_USER_MEMBER
		IF  NVL(old.EMAIL, 'x') !=  NVL(obj.EMAIL, 'x')  OR NVL(old.TEL, 'x') !=  NVL(obj.TEL, 'x')  OR NVL(old.CELL, 'x') !=  NVL(obj.CELL, 'x')  OR NVL(old.MEMBER_PW, 'x') !=  NVL(obj.MEMBER_PW, 'x')  OR NVL(old.GROUP_SEQ, -1) !=  NVL(obj.GROUP_SEQ, -1)
       EXECUTE  
       INSERT INTO MC_USER_MEMBER_HISTORY(
	        SEQ, MEMBER_ID, MEMBER_NM, CONTS, MOD_ID, MOD_NM, MOD_DT, MOD_IP
	    ) VALUES(
	       SEQ_MC_USER_MEMBER_HISTORY.NEXTVAL, obj.MEMBER_ID, obj.MEMBER_NM, '<p>이메일 : ' || obj.EMAIL || '</p><p>전화번호 : ' || old.TEL || '</p><p>휴대전화 : ' || old.CELL || '</p>', obj.MOD_ID,  obj.MOD_NM, obj.MOD_DT, obj.MOD_IP	      
	    );	    